version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # Correctly refer to the named volume
      - ./init:/docker-entrypoint-initdb.d  # Initialize the database
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:  # Ensure named volume is declared here
